--- 
ruby-1.9.2-p0.tar.gz: 
  :md5: 755aba44607c580fddc25e7c89260460
  :path_prefix: ruby-lang/1.9/
  :url: ftp://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.2-p0.tar.gz
ruby-1.9.1-p378.tar.gz: 
  :md5: 9fc5941bda150ac0a33b299e1e53654c
  :path_prefix: ruby-lang/1.9/
  :url: ftp://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.1-p378.tar.gz
ruby-1.8.7-p302.tar.gz: 
  :md5: a6a9e37079ed8cf8726b455dad3de939
  :path_prefix: ruby-lang/1.8/
  :url: ftp://ftp.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7-p302.tar.gz
ruby-1.8.6-p399.tar.gz: 
  :md5: c3d16cdd3c1ee8f3b7d1c399d4884e33
  :path_prefix: ruby-lang/1.8/
  :url: ftp://ftp.ruby-lang.org/pub/ruby/1.8/ruby-1.8.6-p399.tar.gz
ruby-1.8.5-p231.tar.gz: 
  :md5: e900cf225d55414bffe878f00a85807c
  :path_prefix: ruby-lang/1.8/
  :url: ftp://ftp.ruby-lang.org/pub/ruby/1.8/ruby-1.8.5-p231.tar.gz
rubygems-1.3.7.tgz: 
  :md5: e85cfadd025ff6ab689375adbf344bbe
  :path_prefix: rubygems/
  :url: http://rubyforge.org/frs/download.php/70696/rubygems-1.3.7.tgz
rubygems-1.3.6.tgz: 
  :md5: 789ca8e9ad1d4d3fe5f0534fcc038a0d
  :path_prefix: rubygems/
  :url: http://rubyforge.org/frs/download.php/69365/rubygems-1.3.6.tgz
rubygems-1.3.5.tgz: 
  :md5: 6e317335898e73beab15623cdd5f8cff
  :path_prefix: rubygems/
  :url: http://rubyforge.org/frs/download.php/60718/rubygems-1.3.5.tgz  
jruby-bin-1.5.3.tar.gz: 
  :md5: ccb0b2dbc300d8dd4ad1bd4da48b8320
  :path_prefix: jruby/1.5.3/
  :url: http://jruby.org.s3.amazonaws.com/downloads/1.5.3/jruby-bin-1.5.3.tar.gz
rubinius-1.1.0-20100923.tar.gz: 
  :md5: e2ae16238b201de09975abe19da09ea9
  :path_prefix: rubinius/
  :url: http://asset.rubini.us/rubinius-1.1.0-20100923.tar.gz
ruby-enterprise-1.8.7-2010.02.tar.gz: 
  :md5: 4df7b09c01adfd711b0ab76837611542
  :path_prefix: ree/
  :url: http://rubyforge.org/frs/download.php/71096/ruby-enterprise-1.8.7-2010.02.tar.gz
MacRuby 0.7.1.zip: 
  :md5: e8245dcd03c0757dfae7e6fee913947a
  :path_prefix: macruby/
  :url: http://www.macruby.org/files/MacRuby%200.7.1.zip